### PR TITLE
Are you accepting pull requests?

### PR DESCRIPTION
**Pull request by rlsutton1**
Hi,
I've done quite a bit of work on this lib and am wondering if you'd like to merge it back to your repo?

I will probably continue updating the lib as I'm about to start integrating it into my existing robot.

changes include:

- Added a Java GUI Demo (see video link in my readme)
- Angle is now a float
- Scan() discards the first (incomplete) scan, and always returns a full scan.
- Added continuous scanning mode
- Removed timed waiting in favor of event driven waits.
- Fixed invalid commands being set to the RPLidar.
- Fixed parsing of incomplete packets of data from the RPLidar.
- Added line numbers to logging
- Replaced JavaTxRx with Lib that has built in native drivers

Regards
Robert.

### CODE REVIEW

**Comment by jabrena** [comment]
Hi Mate, yes of course, but this repository is deprecated, the development continued here:
https://github.com/ev3dev-lang-java/usb-devices/tree/develop

Now, the driver has a support for A2 with better sample rate. Review the new development and if you have better code, I could merge it.

Cheers

Juan Antonio

**Comment by jabrena** [comment]
It is nice, @rlsutton1.

I will review the code with A1 and A2.
Give me some days to send you the feedback.

Nice video:
https://www.youtube.com/watch?v=nKdeGhDYD48

Juan Antonio

**Comment by rlsutton1** [comment]
Thanks Juan, Happy to wait.

BTW, do you happen to know what size the thread is in the mounting holes of the A1?

Robert.

**Comment by jabrena** [comment]
This weekend, I will test the code with a real device.

**Pull request closed without merging**
